const defaultChartOfAccountNewUnit = [
  {
    subClassCode: "110",
    code: "11000",
    name: "Kas",
    createdBy: "system",
  },
  {
    subClassCode: "110",
    code: "11010",
    name: "Kas Kecil",
    createdBy: "system",
  },
  {
    subClassCode: "120",
    code: "12000",
    name: "Bank",
    createdBy: "system",
  },
  {
    subClassCode: "130",
    code: "13000",
    name: "Piutang Usaha",
    createdBy: "system",
  },
  {
    subClassCode: "130",
    code: "13001",
    name: "Piutang Belum Ditagih",
    createdBy: "system",
  },
  {
    subClassCode: "131",
    code: "13100",
    name: "Piutang Giro",
    createdBy: "system",
  },
  {
    subClassCode: "132",
    code: "13200",
    name: "Piutang Karyawan",
    createdBy: "system",
  },
  {
    subClassCode: "132",
    code: "13299",
    name: "Piutang Lainnya",
    createdBy: "system",
  },
  {
    subClassCode: "133",
    code: "13300",
    name: "Cadangan Piutang Tak tertagih",
    createdBy: "system",
  },
  {
    subClassCode: "140",
    code: "14000",
    name: "Persediaan",
    createdBy: "system",
  },
  {
    subClassCode: "140",
    code: "14010",
    name: "Persediaan Diterima Belum Ditagihkan",
    createdBy: "system",
  },
  {
    subClassCode: "141",
    code: "14100",
    name: "Persediaan Barang Setengah Jadi",
    createdBy: "system",
  },
  {
    subClassCode: "142",
    code: "14200",
    name: "Persediaan Bahan Baku",
    createdBy: "system",
  },
  {
    subClassCode: "150",
    code: "15000",
    name: "Pendapatan Yang Masih Harus Diterima",
    createdBy: "system",
  },
  {
    subClassCode: "151",
    code: "15100",
    name: "Uang Muka Pembelian",
    createdBy: "system",
  },
  {
    subClassCode: "151",
    code: "15110",
    name: "Uang Muka Pembelian Harta Tetap",
    createdBy: "system",
  },
  {
    subClassCode: "152",
    code: "15200",
    name: "Beban Dibayar Dimuka",
    createdBy: "system",
  },
  {
    subClassCode: "153",
    code: "15300",
    name: "PPh 21 Dibayar Dimuka",
    createdBy: "system",
  },
  {
    subClassCode: "153",
    code: "15301",
    name: "PPh 22 Dibayar Dimuka",
    createdBy: "system",
  },
  {
    subClassCode: "153",
    code: "15302",
    name: "PPh 23 Dibayar Dimuka",
    createdBy: "system",
  },
  {
    subClassCode: "153",
    code: "15303",
    name: "PPh 25 Dibayar Dimuka",
    createdBy: "system",
  },
  {
    subClassCode: "154",
    code: "15400",
    name: "PPN Masukan",
    createdBy: "system",
  },
  {
    subClassCode: "155",
    code: "15500",
    name: "Investasi Jangka Pendek",
    createdBy: "system",
  },
  {
    subClassCode: "159",
    code: "15900",
    name: "Aktiva Lancar Lainnya",
    createdBy: "system",
  },
  {
    subClassCode: "160",
    code: "16000",
    name: "Tanah",
    createdBy: "system",
  },
  {
    subClassCode: "161",
    code: "16100",
    name: "Bangunan",
    createdBy: "system",
  },
  {
    subClassCode: "162",
    code: "16200",
    name: "Kendaraan",
    createdBy: "system",
  },
  {
    subClassCode: "163",
    code: "16300",
    name: "Mesin dan Peralatan",
    createdBy: "system",
  },
  {
    subClassCode: "164",
    code: "16400",
    name: "Peralatan Kantor",
    createdBy: "system",
  },
  {
    subClassCode: "169",
    code: "16900",
    name: "Harta Lainnya",
    createdBy: "system",
  },
  {
    subClassCode: "171",
    code: "17100",
    name: "Akumulasi Penyusutan Bangunan",
    createdBy: "system",
  },
  {
    subClassCode: "172",
    code: "17200",
    name: "Akumulasi Penyusutan Kendaraan",
    createdBy: "system",
  },
  {
    subClassCode: "173",
    code: "17300",
    name: "Akumulasi Penyusutan Mesin dan Peralatan",
    createdBy: "system",
  },
  {
    subClassCode: "174",
    code: "17400",
    name: "Akumulasi Penyusutan Peralatan Kantor",
    createdBy: "system",
  },
  {
    subClassCode: "179",
    code: "17900",
    name: "Akumulasi Penyusutan Harta Lainnya",
    createdBy: "system",
  },
  {
    subClassCode: "180",
    code: "18000",
    name: "Investasi Jangka Panjang",
    createdBy: "system",
  },
  {
    subClassCode: "190",
    code: "19000",
    name: "Goodwill",
    createdBy: "system",
  },
  {
    subClassCode: "199",
    code: "19900",
    name: "Aktiva Tidak Berwujud Lainnya",
    createdBy: "system",
  },
  {
    subClassCode: "210",
    code: "21000",
    name: "Hutang Usaha",
    createdBy: "system",
  },
  {
    subClassCode: "210",
    code: "21001",
    name: "Hutang Belum Ditagih",
    createdBy: "system",
  },
  {
    subClassCode: "211",
    code: "21100",
    name: "Hutang Giro",
    createdBy: "system",
  },
  {
    subClassCode: "212",
    code: "21200",
    name: "Utang Gaji dan Upah",
    createdBy: "system",
  },
  {
    subClassCode: "220",
    code: "22000",
    name: "Pendapatan Diterima Dimuka",
    createdBy: "system",
  },
  {
    subClassCode: "220",
    code: "22010",
    name: "Persediaan Dikirim Belum Ditagihkan",
    createdBy: "system",
  },
  {
    subClassCode: "221",
    code: "22100",
    name: "Uang Muka Penjualan",
    createdBy: "system",
  },
  {
    subClassCode: "222",
    code: "22200",
    name: "Beban Yang Masih Harus Dibayar",
    createdBy: "system",
  },
  {
    subClassCode: "230",
    code: "23000",
    name: "Utang PPh 21",
    createdBy: "system",
  },
  {
    subClassCode: "230",
    code: "23001",
    name: "Utang PPh 22",
    createdBy: "system",
  },
  {
    subClassCode: "230",
    code: "23002",
    name: "Utang PPh 23",
    createdBy: "system",
  },
  {
    subClassCode: "230",
    code: "23003",
    name: "Utang PPh 29",
    createdBy: "system",
  },
  {
    subClassCode: "230",
    code: "23099",
    name: "Utang Pajak Lainnya",
    createdBy: "system",
  },
  {
    subClassCode: "231",
    code: "23100",
    name: "PPN Keluaran",
    createdBy: "system",
  },
  {
    subClassCode: "249",
    code: "24900",
    name: "Utang Dividen",
    createdBy: "system",
  },
  {
    subClassCode: "249",
    code: "24999",
    name: "Utang Jangka Pendek Lainnya",
    createdBy: "system",
  },
  {
    subClassCode: "250",
    code: "25000",
    name: "Utang Bank",
    createdBy: "system",
  },
  {
    subClassCode: "299",
    code: "29900",
    name: "Utang Jangka Panjang Lainnya",
    createdBy: "system",
  },
  {
    subClassCode: "310",
    code: "31000",
    name: "Modal Disetor",
    createdBy: "system",
  },
  {
    subClassCode: "320",
    code: "32000",
    name: "Laba Ditahan",
    createdBy: "system",
  },
  {
    subClassCode: "330",
    code: "33000",
    name: "Dividen",
    createdBy: "system",
  },
  {
    subClassCode: "399",
    code: "39900",
    name: "Laba Periode Berjalan",
    createdBy: "system",
  },
  {
    subClassCode: "410",
    code: "41000",
    name: "Penjualan",
    createdBy: "system",
  },
  {
    subClassCode: "410",
    code: "41001",
    name: "Pendapatan Belum Ditagih",
    createdBy: "system",
  },
  {
    subClassCode: "420",
    code: "42000",
    name: "Retur Penjualan",
    createdBy: "system",
  },
  {
    subClassCode: "430",
    code: "43000",
    name: "Diskon Penjualan",
    createdBy: "system",
  },
  {
    subClassCode: "510",
    code: "51000",
    name: "Harga Pokok Penjualan",
    createdBy: "system",
  },
  {
    subClassCode: "511",
    code: "51100",
    name: "Beban Pengiriman",
    createdBy: "system",
  },
  {
    subClassCode: "511",
    code: "51101",
    name: "Beban Parkir",
    createdBy: "system",
  },
  {
    subClassCode: "519",
    code: "51900",
    name: "Penyesuaian Persediaan",
    createdBy: "system",
  },
  {
    subClassCode: "520",
    code: "52000",
    name: "Retur Pembelian",
    createdBy: "system",
  },
  {
    subClassCode: "530",
    code: "53000",
    name: "Diskon Pembelian",
    createdBy: "system",
  },
  {
    subClassCode: "540",
    code: "54000",
    name: "Beban Atas Pembelian",
    createdBy: "system",
  },
  {
    subClassCode: "550",
    code: "55000",
    name: "Beban Tenaga Kerja Lansung",
    createdBy: "system",
  },
  {
    subClassCode: "560",
    code: "56000",
    name: "Beban Overhead Pabrik",
    createdBy: "system",
  },
  {
    subClassCode: "610",
    code: "61000",
    name: "Beban Iklan",
    createdBy: "system",
  },
  {
    subClassCode: "610",
    code: "61001",
    name: "Beban Promosi",
    createdBy: "system",
  },
  {
    subClassCode: "610",
    code: "61002",
    name: "Beban Transportasi Sales",
    createdBy: "system",
  },
  {
    subClassCode: "610",
    code: "61003",
    name: "Beban Komunikasi Sales",
    createdBy: "system",
  },
  {
    subClassCode: "610",
    code: "61004",
    name: "Beban Komisi Sales",
    createdBy: "system",
  },
  {
    subClassCode: "610",
    code: "61099",
    name: "Beban Sales Lainnya",
    createdBy: "system",
  },
  {
    subClassCode: "620",
    code: "62000",
    name: "Beban Upah dan Gaji",
    createdBy: "system",
  },
  {
    subClassCode: "620",
    code: "62001",
    name: "Beban Tunjangan Hari Raya",
    createdBy: "system",
  },
  {
    subClassCode: "620",
    code: "62002",
    name: "Beban Tunjangan Makan",
    createdBy: "system",
  },
  {
    subClassCode: "620",
    code: "62003",
    name: "Beban Tunjangan Transportasi",
    createdBy: "system",
  },
  {
    subClassCode: "620",
    code: "62004",
    name: "Beban BPJS Kesehatan",
    createdBy: "system",
  },
  {
    subClassCode: "620",
    code: "62005",
    name: "Beban BPJS Ketenagakerjaan",
    createdBy: "system",
  },
  {
    subClassCode: "620",
    code: "62099",
    name: "Beban Tenaga Kerja Lainnya",
    createdBy: "system",
  },
  {
    subClassCode: "630",
    code: "63000",
    name: "Beban Air",
    createdBy: "system",
  },
  {
    subClassCode: "630",
    code: "63001",
    name: "Beban Listrik",
    createdBy: "system",
  },
  {
    subClassCode: "630",
    code: "63002",
    name: "Beban Telepon",
    createdBy: "system",
  },
  {
    subClassCode: "630",
    code: "63003",
    name: "Beban Internet",
    createdBy: "system",
  },
  {
    subClassCode: "630",
    code: "63004",
    name: "Beban Berlanggan Aplikasi",
    createdBy: "system",
  },
  {
    subClassCode: "630",
    code: "63005",
    name: "Beban Iuran",
    createdBy: "system",
  },
  {
    subClassCode: "630",
    code: "63099",
    name: "Beban Utilitas Lainnya",
    createdBy: "system",
  },
  {
    subClassCode: "640",
    code: "64000",
    name: "Beban Pemeliharran Kendaraan",
    createdBy: "system",
  },
  {
    subClassCode: "640",
    code: "64001",
    name: "Beban Pemeliharaan Bangunan",
    createdBy: "system",
  },
  {
    subClassCode: "640",
    code: "64002",
    name: "Beban Pemeliharaan Mesin",
    createdBy: "system",
  },
  {
    subClassCode: "640",
    code: "64099",
    name: "Beban Pemeliharaan Lainnya",
    createdBy: "system",
  },
  {
    subClassCode: "650",
    code: "65000",
    name: "Beban Sewa Kendaraan",
    createdBy: "system",
  },
  {
    subClassCode: "650",
    code: "65001",
    name: "Beban Sewa Tanah dan Bangunan",
    createdBy: "system",
  },
  {
    subClassCode: "650",
    code: "65002",
    name: "Beban Sewa Mesin",
    createdBy: "system",
  },
  {
    subClassCode: "650",
    code: "65099",
    name: "Beban Sewa Lainnya",
    createdBy: "system",
  },
  {
    subClassCode: "660",
    code: "66000",
    name: "Beban Perijinan dan Lisensi",
    createdBy: "system",
  },
  {
    subClassCode: "670",
    code: "67100",
    name: "Beban Penyusutan Bangunan",
    createdBy: "system",
  },
  {
    subClassCode: "670",
    code: "67200",
    name: "Beban Penyusutan Kendaraan",
    createdBy: "system",
  },
  {
    subClassCode: "670",
    code: "67300",
    name: "Beban Penyusutan Mesin dan Peralatan",
    createdBy: "system",
  },
  {
    subClassCode: "670",
    code: "67400",
    name: "Beban Penyusutan Peralatan Kantor",
    createdBy: "system",
  },
  {
    subClassCode: "670",
    code: "67500",
    name: "Beban Penyusutan Harta Lainnya",
    createdBy: "system",
  },
  {
    subClassCode: "680",
    code: "68000",
    name: "Beban Piutang Tak tertagih",
    createdBy: "system",
  },
  {
    subClassCode: "690",
    code: "69000",
    name: "Beban Merchant Discount Rate (IDR)",
    createdBy: "system",
  },
  {
    subClassCode: "690",
    code: "69999",
    name: "Beban Operasional Lainnya",
    createdBy: "system",
  },
  {
    subClassCode: "710",
    code: "71000",
    name: "Pendapatan Dividen",
    createdBy: "system",
  },
  {
    subClassCode: "711",
    code: "71100",
    name: "Pendapatan Bunga Bank",
    createdBy: "system",
  },
  {
    subClassCode: "720",
    code: "72000",
    name: "Laba Rugi Penjualan Aktiva Tetap",
    createdBy: "system",
  },
  {
    subClassCode: "730",
    code: "73000",
    name: "Selisih Kurs",
    createdBy: "system",
  },
  {
    subClassCode: "740",
    code: "74000",
    name: "Selisih Nilai Investasi",
    createdBy: "system",
  },
  {
    subClassCode: "799",
    code: "79900",
    name: "Pendapatan Non Operasional Lainnya",
    createdBy: "system",
  },
  {
    subClassCode: "810",
    code: "81000",
    name: "Beban Administrasi Bank",
    createdBy: "system",
  },
  {
    subClassCode: "810",
    code: "81001",
    name: "Beban Denda Bank",
    createdBy: "system",
  },
  {
    subClassCode: "810",
    code: "81002",
    name: "Beban Provisi dan Administrasi Bank atas Pinjaman",
    createdBy: "system",
  },
  {
    subClassCode: "810",
    code: "81003",
    name: "Beban Bunga",
    createdBy: "system",
  },
  {
    subClassCode: "899",
    code: "89900",
    name: "Beban Non Operasional Lainnnya",
    createdBy: "system",
  },
  {
    subClassCode: "910",
    code: "91000",
    name: "Pajak Penghasilan",
    createdBy: "system",
  },
  {
    subClassCode: "910",
    code: "91001",
    name: "Pajak Penghasilan Ditangguhkan",
    createdBy: "system",
  },
  {
    subClassCode: "920",
    code: "92000",
    name: "Beban Pajak Lainnya",
    createdBy: "system",
  },
];

export default defaultChartOfAccountNewUnit;